#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/cloud_1
- name: Configure System
  import_tasks: servers.yml

- name: Configure Firewall
  import_tasks: ufw.yml

- name: Install Docker ecosystem
  import_tasks: docker.yml

