#SPDX-License-Identifier: MIT-0
---
# vars file for roles/cloud_1
db_root_password: "{{ vault_db_root_password }}"
db_name: "{{ vault_db_name }}"
db_user: "{{ vault_db_user }}"
db_password: "{{ vault_db_password }}"
