$ANSIBLE_VAULT;1.1;AES256
36613138333132653730303630323332373131616334653133346664636131366661643535646661
6566643634666639343836626461383366633130366137630a356233316531656333313365613139
62313062373764643263643035373431326237666562323466633666336439643066373336616131
6134323033613334390a646561356436383366333939323236626566336564633164363238316164
66383234306436613637376165356436626434323866303432356238616462333662366364313930
64303531643733303734663137626466393762356232623837646139353531383365663236643462
35633462376637643734633066643632356236613436373765376537303334626630663930623938
32616639613362663336363534623866396534646166346232666165323136336433393564653162
64623464366564616663623534343732376536343061343836623036303162303664376539346236
37376332323438393562636232303564653163373939656537383139383136313663313030376633
623235646332313164653162396466663863
